### ISSUE TITLE
Filled Text Position Off

### ISSUE THREAD

**Issue by simplyjt** [galkahana/HummusJSSamples#12]
Hi, I used this sample code to test form filling on a pdf with fields that I created in adobe acrobat. After I run the code and open the newly created pdf. Although each text is in the correct field, the text is positioned at the bottom left corner of the field, with half of the text cut off. This happens even if I set the field to align center. What's even weirder is when I input text manually into the field using acrobat, it displays just fine. I don't know why this is happening.

**Comment by simplyjt** [comment]
Never mind. I found the TD() operator for positioning.

**Comment by wemaro** [comment]
Can you elaborate on how you fixed this? Maybe share your code? I think I'm facing the same issue now..

**Comment by simplyjt** [comment]
In the sample code pdf-form-fill.js there's a function called writeAppearanceXObjectForText. Here's the part of the function where I added the TD() operator

xobjectForm.getContentContext()
        .writeFreeCode('/Tx BMC\r\n')
        .q()
        .BT()
        .writeFreeCode(da + '\r\n')
	.TD(0,4.5)
        .Tj(text,{encoding:'code'})
        .ET()
        .Q()
        .writeFreeCode('EMC')

**Comment by wemaro** [comment]
Great, thanks for the quick response! It's working perfect now!

**Comment by MityaDSCH** [comment]
I'm also running into problems with the default alignment of filled fields when using the pdf-form-fill.js script. I'm hoping that there's some way to set a default alignment for the form XObject that gets created in [writeAppearanceXObjectForText()](https://github.com/galkahana/HummusJSSamples/blob/master/filling-form-values/pdf-form-fill.js#L137).

Manually setting a y-offset using TD worked well enough for me, but I'm trying to fill in a form that has fields that should have a mixture of horizontal alignments. [There's a comment](https://github.com/galkahana/HummusJSSamples/blob/master/filling-form-values/pdf-form-fill.js#L164) mentioning that you're not supporting the quadding of the containing acroform. My pdf knowledge is decidedly shaky, but I think "supporting" this would give me correct horizontal alignment in the form I'm trying to fill. If anyone has some pointers on edits I might make to happen I'd love to have them!
