### ISSUE TITLE
hey, can you please provide example on how to fill in a pdf form ?

### ISSUE THREAD

**Issue by jpca999** [galkahana/HummusJSSamples#4]

**Comment by galkahana** [comment]
there's something i started here:
https://github.com/galkahana/HummusJSSamples/tree/form-filling

if you want to have a look. not complete...and there's some bugs, but maybe can help you

**Comment by galkahana** [comment]
it's now available in master, and is complete. have fun

**Comment by jpca999** [comment]
I appreciate it sir.
